#指定运行环境
language: node_js
#指定nodejs版本，可以指定多个
node_js:
  - lts/*

cache:
  directories:
    - node_modules
#运行的脚本命令
script:
  - vuepress build

after_script:
  - cd .vuepress/dist
  - echo 'smalin.cn' > CNAME
  - git init
  - git config user.name "${NAME}"
  - git config user.email "${EMAIL}"
  - git add .
  - git commit -m 'auto-deploy'
  - git push -f "https://${TOKEN}@${REF}" master:${BRANCH}

#指定分支，只有指定的分支提交时才会运行脚本
branches:
  only:
    - master