language: node_js
node_js:
- lts/*
cache:
  directories:
  - node_modules
script:
- vuepress build
after_script:
- cd .vuepress/dist
- echo 'smalin.cn' > CNAME
- git init
- git config user.name "${NAME}"
- git config user.email "${EMAIL}"
- git add .
- git commit -m 'auto-deploy'
- git push -f git@github.com:smalin0020/myBlog.git master:${BRANCH}
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_4f2608293004_key -iv $encrypted_4f2608293004_iv
  -in .travis/travisCI.enc -out ~/.ssh/travisCI -d
